---
title: "Political Effectuation - Sequence and Stability"
author: "Peter Boumgarden and Mark Hand"
date: "5/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message=FALSE, warning=FALSE)
```

## Introduction

The following document walks through an analysis of political effectuation in the form of ideological exploration for candidates for senate and house in the US political races, in particular exploring whether they funding maintained stability or had any sort of sequence in ideological homogeneity.

```{r comment=NA, warning=FALSE, message=FALSE} 
# Installing Necessary Packages
source("http://washuresearch.org/stockfunctions.R") 
library(tidyverse) 
library(ff)
library(data.table)
```

## Data Cleaning 

```{r comment=NA, warning=FALSE, message=FALSE} 
# https://data.stanford.edu/dime#download-data
# https://elections.huffingtonpost.com/pollster/2014-national-house-race

# Loading Data for Analysis
# Shouldn't be necessary if you open in RProj 
# fread("Political_Data/dime_cong_elections_current.csv", select = c(1:3))
# PoliticalIdeology <- read_csv("Political_Data/dime_cong_elections_current.csv")
# contribDB_2014 <- fread("Political_Data/contribDB_2014.csv", select = c("amount","date","contributor.name","contributor.zipcode","recipient.name","seat","contributor.cfscore", "candidate.cfscore"))

# View(contribDB_2014)

# PoliticalIdeology %>% transform(total_receipts = as.numeric(total_receipts)) -> PoliticalIdeology

# Sample Candidate Filter for Alquist and Beta
# Candidate.Funding_Alquist <- filter(contribDB_2014, recipient.name == "alquist, elaine")
# Candidate.Funding_Beto <- filter(contribDB_2014, recipient.name == "O ROURKE, ROBERT (BETO)")

```

```{r some fun charts, include=F}
# http://r4ds.had.co.nz/data-visualisation.html

# All data, by party
ggplot(data = PoliticalIdeology) + 
  geom_point(mapping = aes(x = recipient_cfscore , y = total_receipts, color=party))

# All data, by win/loss
ggplot(data = PoliticalIdeology) + 
  geom_point(mapping = aes(x = recipient_cfscore , y = total_receipts, color=gwinner))

# Republican winners and losers 
ggplot(data = subset(PoliticalIdeology, party=="R")) + 
  geom_point(mapping = aes(x = recipient_cfscore , y = total_receipts, color=gwinner))

# Subset
ggplot(data = subset(PoliticalIdeology, total_receipts > 400000)) + 
  geom_point(mapping = aes(x = recipient_cfscore , y = total_receipts, color=gwinner))

# Texas 2018 
ggplot(data = subset(PoliticalIdeology, state=="TX" & cycle=="2018")) + 
  geom_point(mapping = aes(x = recipient_cfscore , y = total_receipts, color=party))

# Histo 
ggplot(data = PoliticalIdeology) +
  geom_histogram(mapping = aes(x = recipient_cfscore))

# Beto2014 
ggplot(data = subset(contribDB_2014, recipient.name == "O ROURKE, ROBERT (BETO)")) + 
  geom_point(mapping = aes(x = date, y = contributor.cfscore, size = amount)) + theme_minimal() + labs(list(title='', x='', y='')) + theme(axis.ticks = element_blank(), axis.text.x = element_blank()) 

# Beto2014 trend line #fail 
ggplot(data = subset(contribDB_2014, recipient.name == "O ROURKE, ROBERT (BETO)")) + geom_point(mapping = aes(x = date, y = contributor.cfscore)) + geom_smooth(mapping = aes(x = date, y = contributor.cfscore), method="lm") + theme_minimal() 

# grep('SCALISE', contribDB_2014$recipient.name) 
contribDB_2014$recipient.name[660490]

"SCALISE, STEPHEN J"
ggplot(data = subset(contribDB_2014, recipient.name == "SCALISE, STEPHEN J")) + 
  geom_point(mapping = aes(x = date, y = contributor.cfscore, size = amount)) + theme_minimal() + labs(list(title='', x='', y='')) + theme(axis.ticks = element_blank(), axis.text.x = element_blank()) 
```
